### ISSUE TITLE
Module not found: qdarktheme

### ISSUE THREAD

**Issue by eikob** [ierror/acid-chess#9]
Followed the instructions how to install and run, but I get the following error:

```
% pipenv run bin/acid-chess   

Traceback (most recent call last):
  File "/Users/user/Desktop/acid-chess/bin/acid-chess", line 7, in <module>
    from acid.app import start  # isort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/acid-chess/bin/../acid/app.py", line 13, in <module>
    import qdarktheme
```

**Comment by ierror** [comment]
Thank you for testing! Have you run 

`pipenv  install`  before the run command? If yes, could you please post the output of `pipenv graph`?

**Comment by eikob** [comment]
I think the first error is the critical one:

```
% pipenv install              
Installing dependencies from Pipfile.lock (f56b21)...
[pipenv.exceptions.InstallError]: Ignoring pyqtdarktheme: markers 'python_version < "3.12" and python_version >= "3.7"' don't match your environment
```
with dozens of lines following. That whole python versioning thing is killing me:

```
% python --version
Python 2.7.18

% python3 --version
Python 3.9.6

% which python3
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3

% /usr/local/bin/python3 --version
Python 3.11.6

% pipenv shell
Launching subshell in virtual environment...
% python --version
Python 3.12.0
```

on macOS Sonoma. I might have installed Python before manually or via brew. Is there an easy way to use a specific Python version in pipenv? It seems to pick 3.12, and the package needs < 3.12.

**Comment by eikob** [comment]
I made some progress by first deleting the old thing `pipenv --rm` and then explicitly setting an older version `pipenv install --python 3.9.6`.

It was still complaining about a missing module, which I installed manually: `pipenv install importlib-resources`

Afterwards, it didn't find my camera on the first run, spamming the console and then crashing.

Next time, it activated my camera (the camera light got on), and I got a screen with a chess board, but before being able to check things out it crashed. 

From there on, it only very shortly activates the camera on start and crashes right way with the following output:

```
% pipenv run bin/acid-chess
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
13:13:50 | System initialized 🥳
2023-12-03 13:13:50.780 Python[60699:7954451] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
13:13:50 | Saving games to /Users/user/Documents/ACID Chess/Games
13:13:50 | Saving training data to /Users/user/Documents/ACID Chess/TrainingData
[1]    60699 segmentation fault  pipenv run bin/acid-chess
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

I have an external camera connected as well if that helped (usualy switched off). But at the moment, getting it to run without crashing seems to be more important...

**Comment by ierror** [comment]
> I made some progress by first deleting the old thing `pipenv --rm` and then explicitly setting an older version `pipenv install --python 3.9.6`.
> 
> It was still complaining about a missing module, which I installed manually: `pipenv install importlib-resources`
> 

Thanks! I will adapt the documentation accordingly.

> Afterwards, it didn't find my camera on the first run, spamming the console and then crashing.
> 
> Next time, it activated my camera (the camera light got on), and I got a screen with a chess board, but before being able to check things out it crashed.
> 
> From there on, it only very shortly activates the camera on start and crashes right way with the following output:
> 
> ```
> % pipenv run bin/acid-chess
> qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
> qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
> qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
> 13:13:50 | System initialized 🥳
> 2023-12-03 13:13:50.780 Python[60699:7954451] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
> 13:13:50 | Saving games to /Users/user/Documents/ACID Chess/Games
> 13:13:50 | Saving training data to /Users/user/Documents/ACID Chess/TrainingData
> [1]    60699 segmentation fault  pipenv run bin/acid-chess
> /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
>   warnings.warn('resource_tracker: There appear to be %d '
> ```
> 
> I have an external camera connected as well if that helped (usualy switched off). But at the moment, getting it to run without crashing seems to be more important...

 What kind of camera are you using?

**Comment by eikob** [comment]
> What kind of camera are you using?

The iMac (Intel based)  has an internal camera that is probably preselected for now, as the green light on it came on for a short flash. I'd connect some Sony cam later, but right now, it's crashing on start so no way to change anything at all.
